# Generated by Django 4.2.5 on 2023-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=20)),
                ("Username", models.CharField(max_length=20)),
                ("Password", models.CharField(max_length=20)),
                ("Status", models.BooleanField(default=False)),
            ],
        ),
    ]
